// <auto-generated />
namespace CalculadoraInt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class telefononorequerido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(telefononorequerido));
        
        string IMigrationMetadata.Id
        {
            get { return "201707111329113_telefononorequerido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
